from .callback import Callback


class ExceptionHandler(Callback):
    pass